# Generated by Django 2.2.24 on 2021-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
