require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'late_limit_27923' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'FBSDKCoreKit' # <- Add this line HERE
  pod 'FBSDKLoginKit' # <- Add this line HERE
  pod 'GoogleSignIn', '~> 6.1.0'# ,_ Add this line HERE
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'Glassfy', '~> 1.4.0'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'late_limit_27923Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

#   post_install do |installer|
#     # flipper_post_install(installer)
#     react_native_post_install(installer)

#       installer.generated_projects.each do |project|
#       project.targets.each do |target|
#         target.build_configurations.each do |config|
#             config.build_settings["DEVELOPMENT_TEAM"] = "9NW5AK9ZW8"
#          end
#     end
#   end
#   end
# end

post_install do |installer|
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete "IPHONEOS_DEPLOYMENT_TARGET"
    end
    case target.name
    when 'RCT-Folly'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
end
