# Generated by Django 2.2.24 on 2021-08-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        ('questions', '0008_question_right_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsAttempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_attempted', to='decks.Decks')),
                ('question_attempted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_attempted', to='questions.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QuestionsAttempted',
                'verbose_name_plural': 'QuestionsAttempted',
            },
        ),
    ]
