# Generated by Django 2.2.24 on 2021-08-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20210810_1416'),
        ('questions_attempted', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsattempted',
            name='question_attempted',
        ),
        migrations.AddField(
            model_name='questionsattempted',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='questionsattempted',
            name='user_answer_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='questionsattempted',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_employee_user'),
        ),
    ]
