# Generated by Django 2.2.24 on 2021-08-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_attempted', '0002_auto_20210814_0855'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionsattempted',
            name='unique_employee_user',
        ),
    ]
