# Generated by Django 2.2.24 on 2021-08-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0003_auto_20210806_1514"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="right_answer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="right_answer",
                to="answers.Answer",
            ),
        ),
    ]
