# Generated by Django 2.2.24 on 2021-08-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20210806_1514'),
        ('questions', '0002_question_right_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(to='answers.Answer'),
        ),
    ]
