# Generated by Django 2.2.24 on 2021-08-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_auto_20210807_0800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="right_answer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="right_answer",
                to="answers.Answer",
            ),
        ),
    ]
