# Generated by Django 2.2.24 on 2021-08-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_auto_20210807_0815"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="right_answer",
        ),
    ]
