# Generated by Django 2.2.24 on 2021-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_right_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.TextField(default=''),
        ),
    ]
