# Generated by Django 2.2.24 on 2021-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
