# Generated by Django 2.2.24 on 2021-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
